spring.application.name=InventoryManagementSystem

# PostgreSQL Database Configuration
#spring.datasource.url=jdbc:postgresql://restaurant-db:5432/restaurant-service-db
spring.datasource.url=jdbc:postgresql://localhost:5432/inventorymanagementsystem-db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver
# JWT Configuration
jwt.secret=your-super-secret-jwt-key-change-this
jwt.expiration=604800000

# CORS Configuration
cors.allowed-origins=http://localhost:3000,http://localhost:5173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=true

# Logging
logging.level.root=INFO
logging.level.com.example.erp=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
server.error.include-binding-errors=always
